create table `member` (
    `id` bigint generated by default as identity,
    `email` varchar(255) not null,
    `is_enable` boolean not null,
    `password` varchar(255) not null,
    `verify_token` varchar(255) not null,
    primary key (id),
    unique key `UK_email` (`email`),
) DEFAULT CHARSET=utf8;

create table `member_roles` not exists `member_roles` (
    member_id bigint not null,
    roles varchar(255),
    foreign key (member_id) references member (id)
) DEFAULT CHARSET=utf8;

INSERT INTO `MEMBER`(ID, EMAIL, PASSWORD, VERIFY_TOKEN, IS_ENABLE)
VALUES (1, 'azqazq195@gmail.com', 'password', 'token', true);
INSERT INTO `MEMBER`(ID, EMAIL, PASSWORD, VERIFY_TOKEN, IS_ENABLE)
VALUES (2, 'azqazq195@naver.com', 'password', 'token', true);

INSERT INTO `MEMBER_ROLES`(MEMBER_ID, ROLES)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO `MEMBER_ROLES`(MEMBER_ID, ROLES)
VALUES (1, 'ROLE_USER');
INSERT INTO `MEMBER_ROLES`(MEMBER_ID, ROLES)
VALUES (2, 'ROLE_USER');
