INSERT INTO MEMBER(ID, EMAIL, PASSWORD, VERIFY_TOKEN, IS_ENABLE)
VALUES (1, 'azqazq195@gmail.com', 'password', 'token', true);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, VERIFY_TOKEN, IS_ENABLE)
VALUES (2, 'azqazq195@naver.com', 'password', 'token', true);

INSERT INTO MEMBER_ROLES(MEMBER_ID, ROLES)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO MEMBER_ROLES(MEMBER_ID, ROLES)
VALUES (1, 'ROLE_USER');
INSERT INTO MEMBER_ROLES(MEMBER_ID, ROLES)
VALUES (2, 'ROLE_USER');
